# 参考：https://aaronfrancis.com/2021/the-perfect-vercel-github-actions-deployment-pipeline

name: cd-frontend
# on: [push]
on:
  push:
    branches:
      # - main
      # - release
      - test
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: 'node_modulesキャッシュ取得'
        uses: actions/cache@v4
        id: client-bun-cache
        with:
          path: 'node_modules'
          key: client-bun-${{ hashFiles('bun.lockb') }}
      - run: bun install
        if: steps.client-bun-cache.outputs.cache-hit != 'true'

      - name: 'Deploy Frontend to Development'
        uses: amondnet/vercel-action@v20
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          vercel-args: '--scope=if-app'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./

      - name: 'Deploy Frontend to Production'
        uses: amondnet/vercel-action@v20
        if: github.event_name == 'push' && github.ref == 'refs/heads/release'
        with:
          vercel-args: '--prod'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./